'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace db303

    Partial Public Class Book
        Public Property ID As Integer
        Public Property Title As String
        Public Property AuthorId As Nullable(Of Integer)
        Public Property PublisherId As Nullable(Of Integer)
        Public Property PublicDate As Nullable(Of Date)
        Public Property Price As Nullable(Of Integer)
    
    End Class

End Namespace
