'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Namespace web463

    Partial Public Class Product
        <Required(ErrorMessage:="{0}は必須項目です")>
        Public Property ID As Integer
        <Required(ErrorMessage:="{0}は必須項目です")>
        Public Property Name As String
        Public Property Price As Integer
    End Class

End Namespace
