'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Namespace web464

    Partial Public Class Product
        Public Property ID As Integer
        Public Property Name As String
        <Range(100, 1000, ErrorMessage:="{0}は{1}から{2}までの間で指定してください")>
        Public Property Price As Integer
    End Class

End Namespace
